Update gfiles.py to handle the deprecation of apiclient library
Do to the removal of the '__version__' attribute from apiclient by google (see discussion: https://github.com/googleapis/google-api-python-client/issues/870), the line in gfiles.py 'from apiclient import discovery, errors' raises 'AttributeError: module 'googleapiclient' has no attribute '__version__'. Per the discussion referenced above, the preferred implementation is now to import from googleapiclient, instead of apiclient, and I've validated that this resolves the error.

To replicate the issue, run  df2gspread.upload() with valid parameters and the AttributeError will be raised.